/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    WdAvatar: (typeof import("@wot-ui/ui/components/wd-avatar/wd-avatar.vue"))["default"];
    WdBadge: (typeof import("@wot-ui/ui/components/wd-badge/wd-badge.vue"))["default"];
    WdButton: (typeof import("@wot-ui/ui/components/wd-button/wd-button.vue"))["default"];
    WdCard: (typeof import("@wot-ui/ui/components/wd-card/wd-card.vue"))["default"];
    WdCell: (typeof import("@wot-ui/ui/components/wd-cell/wd-cell.vue"))["default"];
    WdCellGroup: (typeof import("@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue"))["default"];
    WdDivider: (typeof import("@wot-ui/ui/components/wd-divider/wd-divider.vue"))["default"];
    WdEmpty: (typeof import("@wot-ui/ui/components/wd-empty/wd-empty.vue"))["default"];
    WdIcon: (typeof import("@wot-ui/ui/components/wd-icon/wd-icon.vue"))["default"];
    WdImg: (typeof import("@wot-ui/ui/components/wd-img/wd-img.vue"))["default"];
    WdInput: (typeof import("@wot-ui/ui/components/wd-input/wd-input.vue"))["default"];
    WdLoading: (typeof import("@wot-ui/ui/components/wd-loading/wd-loading.vue"))["default"];
    WdNavbar: (typeof import("@wot-ui/ui/components/wd-navbar/wd-navbar.vue"))["default"];
    WdPicker: (typeof import("@wot-ui/ui/components/wd-picker/wd-picker.vue"))["default"];
    WdPopup: (typeof import("@wot-ui/ui/components/wd-popup/wd-popup.vue"))["default"];
    WdSearch: (typeof import("@wot-ui/ui/components/wd-search/wd-search.vue"))["default"];
    WdSidebar: (typeof import("@wot-ui/ui/components/wd-sidebar/wd-sidebar.vue"))["default"];
    WdSidebarItem: (typeof import("@wot-ui/ui/components/wd-sidebar-item/wd-sidebar-item.vue"))["default"];
    WdSwiper: (typeof import("@wot-ui/ui/components/wd-swiper/wd-swiper.vue"))["default"];
    WdTab: (typeof import("@wot-ui/ui/components/wd-tab/wd-tab.vue"))["default"];
    WdTabs: (typeof import("@wot-ui/ui/components/wd-tabs/wd-tabs.vue"))["default"];
    WdTag: (typeof import("@wot-ui/ui/components/wd-tag/wd-tag.vue"))["default"];
    WdText: (typeof import("@wot-ui/ui/components/wd-text/wd-text.vue"))["default"];
    WdTextarea: (typeof import("@wot-ui/ui/components/wd-textarea/wd-textarea.vue"))["default"];
    WdToast: (typeof import("@wot-ui/ui/components/wd-toast/wd-toast.vue"))["default"];
  }
}
